Update Headers for 2021
jhipster/prettier-java pull request #450
Opened 2021-01-04 15:01 UTC by DanielFran

## What changed with this PR:

## Example

```java
// Input

// Output

```

## Relative issues or prs:

2021-01-05 06:00 UTC, pascalgrimaud requested changes
The tests should not be changed

2021-03-13 16:10 UTC, pascalgrimaud approved these changes

2021-03-13 17:34 UTC, clementdessoude commented
Sorry @DanielFran I completely missed this PR ! You could have merged it :) 

Thanks anyway !!

2021-03-13 17:35 UTC, clementdessoude approved these changes

2021-03-13 17:54 UTC, merged